version: '3'

services:
  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: pwd
      MARIADB_DATABASE: test_data
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    volumes:
      # persist data files into `datadir` volume managed by docker
      - datadir:/var/lib/mysql
      # bind-mount any sql files that should be run while initializing
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  datadir:
networks:
    net:
        ipam:
            driver: default
            config:
                - subnet: 192.168.39.1/30
    host:
        name: host
        external: true